# Template configuration for Convertigo project CI build on GitHub Actions
# Please consult the GitHub documentation for details about settings
# https://docs.github.com/en/actions
#
# Discover all tasks and -Pconvertigo options in your project build.gradle file.

name: Convertigo CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ ci ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v1.4.3
      with:
        java-version: '11'
    - name: Run Convertigo build
      run: |
        echo "Build the Mobile Application and make a .car" && \
        sh gradlew --no-daemon --stacktrace --info car
    - name: Upload Convertigo .car file
      uses: actions/upload-artifact@v2
      with:
        name: lib_FlowViewer.car
        path: build/lib_FlowViewer.car